### ISSUE TITLE
Error after newest SteamOS update

### ISSUE THREAD

**Issue by chloyster** [davocarli/sharedeck-y#12]
Hey there, a few extensions have been broken since SteamOS updated to 3.5.19 and this is one of them

The error decky displays when trying to view the plugin says

```
TypeError: Cannot read properties of undefined (reading 'Field')
    at eval (eval at importReactPlugin (http://localhost:1337/frontend/chunk-ecb27f3b.js:6994:43), <anonymous>:831:68)
    at eval (eval at importReactPlugin (http://localhost:1337/frontend/chunk-ecb27f3b.js:6994:43), <anonymous>:1129:3)
    at PluginLoader.importReactPlugin (http://localhost:1337/frontend/chunk-ecb27f3b.js:6994:43)
    at async PluginLoader.importPlugin (http://localhost:1337/frontend/chunk-ecb27f3b.js:6969:17)
```

Followed by

```
Loading DeckSettings caused an exception as shown above. This usually means that the plugin requires an update for the new version of SteamUI. Check if an update is present or evaluate its removal in the Decky settings, in the Plugins section.
```

**Comment by oxivanisher** [comment]
I also have this issue. Reinstalling did also not solve this issue.

**Comment by ArthurSmoke** [comment]
+1

**Comment by davocarli** [comment]
An update has already been submitted to the store to resolve this issue, but it has not yet finished going through testing/approval.

**Comment by Fofer** [comment]
Same issue here. Looking forward to the update being publicly released. Thanks!

**Comment by doodhout** [comment]
This plugin (v1.3.0-1) doesn't seem to work on my deck running SteamOS v3.5.19, are we waiting for a version newer than 1.3.0 or should that version work for me?

**Comment by andy-bell101** [comment]
Looks like the update PR has been approved and merged but the build action failed to upload due to a duplicate version number. I'm not sure whose responsibility it is to fix that.

https://github.com/SteamDeckHomebrew/decky-plugin-database/actions/runs/10269774024

As an aside the plugin seems to have disappeared from the store now entirely. I've been trying to get to the bottom of exactly why it's missing but the documentation for the store isn't great

Edit: the decky store lists the plugin as "not visible" so it's definitely not just my deck https://plugins.deckbrew.xyz/admin/#/plugins

**Comment by seannymurrs** [comment]
I'm noticing the same thing (plugin isn't listed on the store anymore). I came here to report it as a bug, and I found this thread. Does anyone know if there's a way to get the plugin to work at this point, or do we need to wait to see when/if an update is released?
